"""add estimated_time to case studies

Revision ID: 54f32e5033cf
Revises: ac7d74f67249
Create Date: 2025-02-23 00:01:58.321754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f32e5033cf'
down_revision: Union[str, None] = 'ac7d74f67249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_studies', sa.Column('estimated_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_studies', 'estimated_time')
    # ### end Alembic commands ###
