"""Add pitfalls column to case_studies

Revision ID: fc94b2a22a41
Revises: 54f32e5033cf
Create Date: 2025-02-24 15:27:42.158117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from casebreaker_backend.mixins import JSONEncodedDict


# revision identifiers, used by Alembic.
revision: str = "fc94b2a22a41"
down_revision: Union[str, None] = "54f32e5033cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_studies", sa.Column("pitfalls", JSONEncodedDict(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_studies", "pitfalls")
    # ### end Alembic commands ###
